### ISSUE TITLE
take urls from hosts.txt

### ISSUE THREAD

**Issue by ghsec** [naquad/bomber#1]
I think it better if you get targets from files, because if I collect hosts from amass, subfinder and other tools is not comfortable write new targets in script.
for example.

```
subfinder -d victimDomain | httpx | bomber
```
it collects subdomains, then checks for HTTP and https services on 80 and 443 ports then ddos with your script

**Comment by ghsec** [comment]
and

**Comment by naquad** [comment]
This is not a security tool per se. Adding capabilities to dynamically specify targets is not its goal.

**If you have some particular resources that should be added then please share here or send a pull request.**
